<?php
$z[0]=Array("field","",95,124);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",143,175);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","\r\n        <div class='news_item wow fadeInUp'>\r\n          <div class='news_item_box'>\r\n            <div class='news_item_time'><span class='a'>[field:pubdate function=\"MyDate('d',@me)\"/]</span><span class='b'>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</span></div>\r\n            <div class='news_item_right'>\r\n              <div class='news_item_title'><a href='[field:arcurl/]'>[field:title /]</a></div>\r\n              <div class='news_item_des'>[field:description/]</div>\r\n            </div>\r\n          </div>\r\n        </div>\r\n        ",242,832);
$z[2][4]=array();
$z[2][4]['titlelen']="42";
$z[2][4]['row']="16";

?>