<?php
$z[0]=Array("field","",14,40);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",50,78);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",80,109);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n          <li><a id=\"lsed\"  href='[field:typeurl/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",157,328);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>