<?php
$z[0]=Array("field","",98,127);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",146,178);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n        <div class='service_item wow fadeInUp' data-wow-delay=\".2s\"><a href='[field:typeurl/]'>\r\n          <div class='service_item_img' style='background:url(/skin/img/z[field:global.autoindex/].jpg) no-repeat center;'></div>\r\n          <div class='service_item_title'>\r\n            <div>[field:typename/]</div>\r\n          </div>\r\n          </a></div>\r\n        ",260,672);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="6";

?>