<div class="art_list wow fadeInUp">
              <div class="art_time2"><span class='day'>[field:pubdate function="MyDate('d',@me)"/]</span><span class='month-year'>[field:pubdate function="MyDate('Y/m',@me)"/]</span></div>
              <div class="art_right art_right2">
                <div class="art_title"><a href='[field:arcurl/]' >[field:title/]</a></div>
                <div class="art_des">[field:description/]</div>
              </div>
            </div>