<?php
$z[0]=Array("global","",349,375);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",399,420);
$z[1][4]=array();
$z[1][4]['name']="cfg_dz";
$z[2]=Array("global","",456,477);
$z[2][4]=array();
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global","",500,521);
$z[3][4]=array();
$z[3][4]['name']="cfg_cz";
$z[4]=Array("global","",556,577);
$z[4][4]=array();
$z[4][4]['name']="cfg_yx";
$z[5]=Array("flink","  [field:link /]  ",631,709);
$z[5][4]=array();
$z[5][4]['titlelen']="40";
$z[5][4]['row']="24";
$z[5][4]['type']="text";
$z[6]=Array("global","",1091,1112);
$z[6][4]=array();
$z[6][4]['name']="cfg_QQ";
$z[7]=Array("global","",1221,1242);
$z[7][4]=array();
$z[7][4]['name']="cfg_QQ";
$z[8]=Array("global","",2512,2533);
$z[8][4]=array();
$z[8][4]['name']="cfg_dh";
$z[9]=Array("global","",2603,2624);
$z[9][4]=array();
$z[9][4]['name']="cfg_dh";
$z[10]=Array("type","<a href=\"[field:typelink/]\"><span class=\"icon-user\"></span>联系</a>",2684,2787);
$z[10][4]=array();
$z[10][4]['typeid']="6";

?>